---
- name: variable playbook test
  hosts: localhost
  
  vars:
    var_1: awesome
    var_2: ansble is
    var_3: "{{ var_1 }} {{ var_3 }}"
    
  tasks:
    
    - name: print {{ var_3 }}
      debug:
        masg: "{{ var_3 }}"